version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: ./server/.env
    expose:
      - 1234
    ports:
      - 1234:1234
    command: sh -c "npm run migrations && npm run dev"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    env_file: ./client/.env
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npm start

  postgres:
    image: postgres:10.4
    expose:
      - 5432
    ports:
      - 35432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docstore
      POSTGRES_DB: docstore
