export const FETCH_FOLDERS = "FETCH_FOLDERS";
export const RECEIVE_FOLDERS = "RECEIVE_FOLDERS";
export const FETCH_FILES = "FETCH_FILES";
export const RECEIVE_FILES = "RECEIVE_FILES";
export const FETCH_SHARED_FILES = "FETCH_SHARED_FILES";
export const RECEIVE_SHARED_FILES = "RECEIVE_SHARED_FILES";